

!$THEME = "eka"

!if %not(%variable_exists("$BGCOLOR"))
!$BGCOLOR = "transparent"
!endif

skinparam backgroundColor $BGCOLOR
skinparam useBetaStyle false

skinparam sequenceArrowThickness 1
skinparam roundcorner 20


skinparam ParticipantPadding 20
skinparam BoxPadding 10

skinparam ActorBorderColor    SaddleBrown
skinparam SequenceReferenceBackgroundColor White
skinparam NoteBackgroundColor White

skinparam SequenceReferenceBorderColor DarkBlue
skinparam SequenceReferenceHeaderBackgroundColor CornflowerBlue
hide footbox

skinparam BoxPadding 20

!$zone = ""
!procedure $zone_add($name)
!$zone = $zone + "participant" + $name + %newline()
!endprocedure

!procedure $service($name, $service, $host="self")
$zone_add($name)
participant os  [
===$host
----
""$service""
]
!endprocedure

!procedure $zone_show($name)
box "eKassir" #Red
## $zone ##
end box
!endprocedure